// Inline the diner's character art + webfonts as base64 so the demo can build
// into a single self-contained HTML file (no external asset fetches, works from
// file://). Run: node demo/gen-assets.mjs  -> writes demo/assets.generated.ts
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const charDir = path.join(root, 'public', 'characters');
const fontDir = path.join(root, 'public', 'fonts');

const b64 = (p) => fs.readFileSync(p).toString('base64');

// --- character textures (key -> data URI), keys match src/ui/assets.ts ---
const CHARACTERS = [
  'housewife', 'businessman', 'kid', 'grandma', 'cowboy',
  'teenager', 'waiter', 'robot', 'alien', 'beatnik',
];
const charEntries = CHARACTERS.map((key) => {
  const uri = `data:image/png;base64,${b64(path.join(charDir, `${key}.png`))}`;
  return `  ${JSON.stringify(key)}: ${JSON.stringify(uri)},`;
}).join('\n');

// --- webfonts, mirroring the @font-face blocks in index.html ---
const FONTS = [
  { family: 'Pacifico', file: 'pacifico.woff2', extra: '' },
  { family: 'Alfa Slab One', file: 'alfa-slab-one.woff2', extra: '' },
  { family: 'Oswald', file: 'oswald-500.woff2', extra: 'font-weight: 500;' },
  { family: 'Oswald', file: 'oswald-700.woff2', extra: 'font-weight: 700;' },
  { family: 'Special Elite', file: 'special-elite.woff2', extra: '' },
];
const fontCss = FONTS.map(({ family, file, extra }) => {
  const uri = `data:font/woff2;base64,${b64(path.join(fontDir, file))}`;
  return `@font-face { font-family: '${family}'; ${extra} src: url('${uri}') format('woff2'); font-display: swap; }`;
}).join('\n');

const out = `// AUTO-GENERATED by demo/gen-assets.mjs — do not edit by hand.
// Base64-inlined art + fonts for the self-contained demo build.

export const CHARACTER_DATA_URIS: Record<string, string> = {
${charEntries}
};

export const FONT_FACE_CSS = ${JSON.stringify(fontCss)};
`;

const dest = path.join(here, 'assets.generated.ts');
fs.writeFileSync(dest, out);
console.log(`wrote ${dest} (${(out.length / 1024).toFixed(0)} KB)`);
